site: jatin
title: jatin-experiments
greetings: Jatin's Experiments
description: >
lang: en-US
timezone: Asia/Kolkata
# repo: https://github.com/h0x0er/blog # site repo [optional]
data-theme: dark # default theme "dark" | "light"
# discus-identifier: powex # replace with your disqus shortname
# comments-enabled: false # true to enable disqus comments, false to hide them
showSearch: true
author:
  name: h0x0er
  bio: ""
  userpicture:
  username: h0x0er # general username
  github: h0x0er # github username
  twitter: # twitter username
  mastodon: # mastodon profile (ex. mastodon.social/@my_username)
  linkedin: jatin-kumar-0a3755168 # linkedin profile
  email: jatink843[at]protonmail[dot]com # email adress

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://h0x0er.github.io" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" #
# baseurl: "" #

markdown: GFM

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled: true
  collections: false
