site_name: Unnamed Memories
site_url: https://h0x0er.github.io/
site_author: jatin
copyright: Copyright &copy; 2025 JATIN KUMAR

nav:
  - index.md
  - Logs:
      - blog/index.md
  - Debug: 
    # - debug/index.md
    - debug/ebpf.md
    - debug/kubernetes.md
  

  # - Experiments:
  #     - experiments/index.md
  # - eBPF: experiments/exp_ebpf.md
  # - Observations:
  # - experiments/observations/index.md
  # - CTF: experiments/observations/ctf.md
  - About:
      - index.md

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips

    # - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking

    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: green
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - blog:
      post_date_format: full
      pagination_per_page: 5
      blog_toc: true
  - meta



extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/jatin-kumar-0a3755168/

    - icon: fontawesome/brands/github 
      link: https://github.com/h0x0er
