authors:
  jatin:
    name: Jatin (h0x0er)
    description: Experimenter
    avatar: "https://avatars.githubusercontent.com/u/84621253?s=400&u=9e35c8575f24fc4af2c56a10f7b22ae83f784705&v=4"
    url: https://www.linkedin.com/in/jatin-kumar-0a3755168/
